name: Release IntelliJ Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Find Plugin File
        id: find_plugin
        run: echo "PLUGIN_FILE=$(find build/distributions -name '*.zip' | head -n 1)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PLUGIN_FILE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body: "New IntelliJ Plugin Release: ${{ github.ref_name }}"
